-- Announcements Table
CREATE TABLE announcements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date VARCHAR(50),
  category VARCHAR(50),
  image_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT true
);

-- Barangay Statistics Table
CREATE TABLE barangay_statistics (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  label VARCHAR(100) NOT NULL UNIQUE,
  value VARCHAR(50) NOT NULL,
  icon_name VARCHAR(100),
  display_order INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Barangay Officials Table
CREATE TABLE barangay_officials (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  photo_url VARCHAR(500),
  contact_email VARCHAR(100),
  contact_phone VARCHAR(20),
  bio TEXT,
  display_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT true
);

-- Assistance Programs Table
CREATE TABLE assistance_programs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  icon_type VARCHAR(50),
  category VARCHAR(100),
  requirements TEXT,
  benefits TEXT,
  contact_person VARCHAR(255),
  contact_number VARCHAR(20),
  display_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT true
);

-- Barangay Events Table
CREATE TABLE barangay_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_date DATE NOT NULL,
  event_time TIME,
  location VARCHAR(255),
  category VARCHAR(100),
  image_url VARCHAR(500),
  organizer VARCHAR(255),
  max_participants INT,
  registration_link VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT true
);

-- Contact Information Table
CREATE TABLE barangay_contact (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contact_type VARCHAR(50) NOT NULL UNIQUE,
  value VARCHAR(255) NOT NULL,
  label VARCHAR(100),
  icon_type VARCHAR(50),
  priority INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Document Types Table
CREATE TABLE document_types (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  price DECIMAL(10, 2) DEFAULT 0,
  processing_days INT DEFAULT 1,
  requirements TEXT,
  icon_type VARCHAR(50),
  category VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS (Row Level Security) for public access
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE barangay_statistics ENABLE ROW LEVEL SECURITY;
ALTER TABLE barangay_officials ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistance_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE barangay_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE barangay_contact ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_types ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for public read access
CREATE POLICY "Allow public read on announcements" ON announcements FOR SELECT USING (is_active = true);
CREATE POLICY "Allow public read on barangay_statistics" ON barangay_statistics FOR SELECT USING (true);
CREATE POLICY "Allow public read on barangay_officials" ON barangay_officials FOR SELECT USING (is_active = true);
CREATE POLICY "Allow public read on assistance_programs" ON assistance_programs FOR SELECT USING (is_active = true);
CREATE POLICY "Allow public read on barangay_events" ON barangay_events FOR SELECT USING (is_active = true);
CREATE POLICY "Allow public read on barangay_contact" ON barangay_contact FOR SELECT USING (is_active = true);
CREATE POLICY "Allow public read on document_types" ON document_types FOR SELECT USING (is_active = true);

-- Insert sample data
INSERT INTO announcements (title, description, date) VALUES
('Barangay Assembly', 'Quarterly Barangay Assembly at Barangay Hall, 9:00 AM', 'June 30, 2024'),
('Free Medical Mission', 'Free checkup, dental, and medicine distribution', 'July 15, 2024'),
('Educational Assistance', 'Scholarship applications now open for qualified students', 'Until July 30');

INSERT INTO barangay_statistics (label, value, display_order) VALUES
('Total Residents', '2,847', 0),
('Households', '712', 1),
('Puroks', '8', 2),
('Digital Services', '99%', 3);

INSERT INTO barangay_officials (name, role, display_order) VALUES
('Hon. Hilarion Nagar', 'Punong Barangay', 0),
('Kagawad Maria R. Santos', 'Barangay Kagawad', 1),
('Kagawad Jose P. Rizal', 'Barangay Kagawad', 2),
('Kagawad Teresa M. Lopez', 'Barangay Kagawad', 3),
('SK Chair Marc Caubanan', 'SK Chairman', 4),
('Ms. Lourdes P. Cruz', 'Barangay Secretary', 5),
('Mr. Ricardo M. Tan', 'Barangay Treasurer', 6);

INSERT INTO document_types (name, price, description) VALUES
('Barangay Clearance', 20, 'Official barangay identification document'),
('Certificate of Indigency', 0, 'Proof of residency for indigent individuals'),
('Certificate of Residency', 0, 'Proof of residency document'),
('Barangay ID', 50, 'Official identification card'),
('Business Clearance', 100, 'Clearance for business operations');

INSERT INTO barangay_contact (contact_type, value, label) VALUES
('address', 'Barangay Hall, Barangay 28, CDO City', 'Address'),
('phone', '(088) 123-4567', 'Phone'),
('email', 'barangay28@cdo.gov.ph', 'Email'),
('emergency_hotline', '0917 123 4567', 'Emergency Hotline');

INSERT INTO assistance_programs (title, description, category) VALUES
('Rice Assistance', 'For Senior Citizens and PWDs', 'Livelihood'),
('Educational Assistance', 'Scholarships for qualified students', 'Education'),
('Medical Assistance', 'For Persons with Disabilities (PWDs)', 'Health'),
('Financial Aid', 'Emergency financial support under 4Ps program', 'Financial'),
('Disaster Relief', 'Assistance during calamities and disasters', 'Emergency');
